let DATA, items=[], byId=new Map(), filter="ALL", aliasMap=new Map(), productMap=new Map(), reverseProducts=new Map();
const $=s=>document.querySelector(s); const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replaceAll("&"," and ").match(/[a-z0-9]+/g)?.join(" ")||"";
async function loadData(){
 const names=["data0.txt","data1.txt","data2.txt","data3a.txt","data3b.txt"];
 const b64=(await Promise.all(names.map(n=>fetch(n).then(r=>{if(!r.ok)throw Error(n);return r.text()})))).join("").trim();
 const raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
 const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream("gzip"));
 DATA=JSON.parse(await new Response(stream).text());
 items=DATA.i.map(r=>({id:r[0],title:r[1],set:r[2],baseline:r[3],strong:r[4],target:r[5],max:r[6]})); items.forEach(x=>byId.set(x.id,x));
 for(const [a,id] of DATA.a){if(!aliasMap.has(a))aliasMap.set(a,[]);aliasMap.get(a).push(id)}
 for(const [n,title,ids] of DATA.p){productMap.set(n,{title,ids});for(const id of ids){if(!reverseProducts.has(id))reverseProducts.set(id,[]);reverseProducts.get(id).push(title)}}
 init();
}
function saved(){try{return JSON.parse(localStorage.getItem("joshSetState"))||null}catch{return null}}function save(s){s.updated=new Date().toISOString();localStorage.setItem("joshSetState",JSON.stringify(s))}function state(){let s=saved();if(!s){s={version:7,owned:items.filter(x=>x.baseline==="OWNED").map(x=>x.id)};save(s)}return s}
function status(x){if(x.set!=="INCLUDED")return x.set;return state().owned.includes(x.id)?"OWNED":"NEEDED"}
function titleKeys(s){let n=norm(s),keys=[n];if(n.startsWith("the "))keys.push(n.slice(4));else keys.push("the "+n);return [...new Set(keys)]}
function collectionInfo(x){let p=null;for(let k of titleKeys(x.title)){p=productMap.get(k);if(p)break}if(!p){let keys=titleKeys(x.title);for(let [k,v] of productMap){let pk=titleKeys(k);if(keys.some(a=>pk.includes(a))){p=v;break}}}if(!p||!p.ids?.length)return null;let covered=[...new Set(p.ids)].map(id=>byId.get(id)).filter(g=>g&&g.set==="INCLUDED");if(!covered.length)return null;return{product:p,covered,owned:covered.every(g=>status(g)==="OWNED")}}
function effectiveStatus(x){let c=collectionInfo(x);return c&&c.owned?"OWNED":status(x)}function progress(){let n=state().owned.filter(id=>byId.get(id)?.set==="INCLUDED").length;$("#progress").textContent=`${n} / ${DATA.n} · ${(n/DATA.n*100).toFixed(2)}%`}
function matches(x,q){if(!q)return true;if(norm(x.title).includes(q))return true;for(const [a,ids] of aliasMap)if(a.includes(q)&&ids.includes(x.id))return true;return false}
function render(){let q=norm($("#q").value);let rows=items.filter(x=>matches(x,q)&&(filter==="ALL"||effectiveStatus(x)===filter)).slice(0,70);$("#results").innerHTML=rows.map(x=>{let c=collectionInfo(x),st=effectiveStatus(x),label=c&&c.owned?"OWNED · COLLECTION":st,sub=c?`${c.owned?"Your collection satisfies":"Collection satisfies"} ${c.covered.length} game ${c.covered.length===1?"identity":"identities"}`:st==="OWNED"?"On your shelf":x.set==="EXCLUDED"?"Outside Josh Set":"Tap for details";return `<article class="card" onclick="detail(${x.id})"><div class="top"><b>${esc(x.title)}</b><span class="badge ${st}">${label}</span></div><div class="sub">${sub}</div></article>`}).join("")||'<p class="muted">Nothing matched.</p>'}
function advice(x,p){if(status(x)==="OWNED")return["SKIP","Already owned."];if(x.set!=="INCLUDED")return["SKIP","Not part of the Josh Set."];if(x.strong!=null&&p<=x.strong)return["GRAB IT",`At/below your $${x.strong} strong-buy price.`];if(x.target!=null&&p<=x.target)return["BUY",`Within your $${x.target} target.`];if(x.max!=null&&p<=x.max)return["FAIR","Reasonable, but above your target."];if(x.max!=null)return["WAIT",`Above your $${x.max} max-reasonable price.`];return["NEED IT","You need it; no personal price profile yet."]}
function detail(id){let x=byId.get(id),c=collectionInfo(x),st=effectiveStatus(x),products=[...new Set(reverseProducts.get(id)||[])];if(c){$("#detail").innerHTML=`<h2>${esc(x.title)}</h2><span class="badge ${c.owned?"OWNED":"REVIEW"}">${c.owned?"OWNED · COLLECTION":"COLLECTION"}</span><p>${c.owned?"This physical collection is on your shelf and already covers the games below.":"This is a physical collection product. It is not counted as an extra game identity; it satisfies the games below."}</p><h3>Satisfies ${c.covered.length} ${c.covered.length===1?"identity":"identities"}</h3><ul class="products">${c.covered.map(g=>`<li><b>${esc(g.title)}</b> · <span class="badge ${status(g)}">${status(g)}</span></li>`).join("")}</ul>`;dlg.showModal();return}$("#detail").innerHTML=`<h2>${esc(x.title)}</h2><span class="badge ${st}">${st}</span>${products.length?`<h3>Physical ways to satisfy it</h3><ul class="products">${products.slice(0,12).map(p=>`<li>${esc(p)}</li>`).join("")}</ul>`:""}${st==="NEEDED"?`<h3>Store Mode</h3><div class="price"><input id="ask" type="number" inputmode="decimal" min="0" step=".01" placeholder="Price"><button onclick="check(${id})">SHOULD I BUY IT?</button></div><div id="v"></div>`:""}`;dlg.showModal()}
function check(id){let p=Number($("#ask").value);if(!Number.isFinite(p))return;let[v,e]=advice(byId.get(id),p);$("#v").innerHTML=`<div class="verdict"><b>${v}</b><br>${esc(e)}</div>`}
const suffixes=["the fire fades edition","ancestral edition","return to castlevania edition","definitive edition","collector s edition","collectors edition","deluxe edition","complete edition","game of the year edition","goty edition"];function candidates(t){let a=[];const add=v=>{let n=norm(v);if(n&&!a.includes(n))a.push(n)};add(t);let nb=t.replace(/\s*\[[^\]]+\]\s*$/,"").trim();if(nb!==t)add(nb);for(let seed of [...a])for(let s of suffixes)if(seed.endsWith(" "+s)){let b=seed.slice(0,-s.length-1).trim();if(b&&!a.includes(b))a.push(b)}return a}
function parseCSV(text){let rows=[],row=[],cell="",q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===","&&!q){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
async function importCSV(f){let rows=parseCSV(await f.text()),h=rows.shift()||[],ix=Object.fromEntries(h.map((x,i)=>[x,i])),owned=new Set(),titles=0,excluded=0,unmatched=[];for(let r of rows){let platform=(r[ix.Platform]||"").trim().toLowerCase(),cat=(r[ix.Category]||"").trim().toLowerCase(),typ=(r[ix.UserRecordType]||"Owned").trim().toLowerCase();if(!["sony playstation 4","playstation 4","ps4"].includes(platform)||cat!=="games"||typ!=="owned")continue;titles++;let title=r[ix.Title]||"",cs=candidates(title),hit=false;for(let c of cs){let p=productMap.get(c);if(p){p.ids.forEach(id=>owned.add(id));hit=true;break}}if(!hit)for(let c of cs){let ids=[];for(let x of items)if(x.set==="INCLUDED"&&norm(x.title)===c)ids.push(x.id);for(let id of aliasMap.get(c)||[])if(byId.get(id)?.set==="INCLUDED")ids.push(id);ids=[...new Set(ids)];if(ids.length){owned.add(ids[0]);hit=true;break}}if(!hit){let isExcluded=cs.some(c=>items.some(x=>x.set==="EXCLUDED"&&norm(x.title)===c)||(aliasMap.get(c)||[]).some(id=>byId.get(id)?.set==="EXCLUDED"));if(isExcluded){excluded++;hit=true}}if(!hit)unmatched.push(title)}save({version:7,owned:[...owned],source:f.name});progress();render();$("#syncmsg").textContent=`GameEye: ${titles} PS4 rows → ${owned.size} satisfied · ${excluded} excluded · ${unmatched.length} unresolved.`;if(unmatched.length)console.warn("Unmatched",unmatched)}
function init(){progress();render();$("#q").oninput=render;document.querySelector("nav").onclick=e=>{if(!e.target.dataset.s)return;filter=e.target.dataset.s;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b===e.target));render()};$("#csv").onchange=e=>{let f=e.target.files[0];if(f)importCSV(f)};$("#backup").onclick=()=>{let b=new Blob([JSON.stringify(state(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="josh-set-backup.json";a.click();URL.revokeObjectURL(a.href)};$("#restoreBtn").onclick=()=>$("#restore").click();$("#restore").onchange=async e=>{try{let s=JSON.parse(await e.target.files[0].text());if(!Array.isArray(s.owned))throw 0;save(s);progress();render();$("#syncmsg").textContent="Backup restored."}catch{$("#syncmsg").textContent="Invalid backup."}}}loadData().catch(e=>{$("#results").innerHTML='<p class="muted">Could not load census data. Refresh once while online.</p>';console.error(e)});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));