let DATA,items=[],byId=new Map(),filter="ALL",aliasesById=new Map(),productMap=new Map(),reverseProducts=new Map(),stateCache,ownedSet=new Set(),productSet=new Set(),priceMap=new Map(),visibleLimit=70;
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’'`]/g,"").replaceAll("&"," and ").match(/[a-z0-9]+/g)?.join(" ")||"";
function rebuildPriceMap(){priceMap=new Map();for(const p of stateCache?.prices||[])if(p?.t)priceMap.set(norm(p.t),p)}
function loadState(){try{stateCache=JSON.parse(localStorage.getItem("joshSetState"))||null}catch{stateCache=null}if(!stateCache)stateCache={version:11,owned:items.filter(x=>x.baseline==="OWNED").map(x=>x.id),products:[],prices:[]};if(!Array.isArray(stateCache.products))stateCache.products=[];if(!Array.isArray(stateCache.prices))stateCache.prices=[];ownedSet=new Set(stateCache.owned||[]);productSet=new Set(stateCache.products||[]);rebuildPriceMap()}
function saveState(s){stateCache=s;s.updated=new Date().toISOString();localStorage.setItem("joshSetState",JSON.stringify(s));ownedSet=new Set(s.owned||[]);productSet=new Set(s.products||[]);rebuildPriceMap()}
async function loadData(){const names=["data0.txt","data1.txt","data2.txt","data3a.txt","data3b.txt"];const b64=(await Promise.all(names.map(n=>fetch(n).then(r=>{if(!r.ok)throw Error(n);return r.text()})))).join("").trim();const raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream("gzip"));DATA=JSON.parse(await new Response(stream).text());items=DATA.i.map(r=>({id:r[0],title:r[1],set:r[2],baseline:r[3],strong:r[4],target:r[5],max:r[6],search:norm(r[1])}));items.forEach(x=>byId.set(x.id,x));for(const[a,id]of DATA.a){if(!aliasesById.has(id))aliasesById.set(id,[]);aliasesById.get(id).push(norm(a))}for(const[n,title,ids]of DATA.p){let key=norm(n),p={key,title,ids};productMap.set(key,p);let noThe=key.startsWith("the ")?key.slice(4):key;productMap.set(noThe,p);for(const id of ids){if(!reverseProducts.has(id))reverseProducts.set(id,[]);reverseProducts.get(id).push(title)}}for(const x of items)x.search+=' '+(aliasesById.get(x.id)||[]).join(' ');loadState();init()}
function status(x){if(x.set!=="INCLUDED")return x.set;return ownedSet.has(x.id)?"OWNED":"NEEDED"}
function findProduct(title){let n=norm(title);return productMap.get(n)||productMap.get(n.startsWith("the ")?n.slice(4):"the "+n)||null}
function collectionInfo(x){let p=findProduct(x.title);if(!p)return null;let covered=[...new Set(p.ids)].map(id=>byId.get(id)).filter(g=>g?.set==="INCLUDED");if(covered.length<2)return null;return{product:p,covered,owned:productSet.has(p.key)}}
function effectiveStatus(x){let c=collectionInfo(x);return c?(c.owned?"OWNED":"NEEDED"):status(x)}
function progress(){let n=0;for(const id of ownedSet)if(byId.get(id)?.set==="INCLUDED")n++;$("#progress").textContent=`${n} / ${DATA.n} · ${(n/DATA.n*100).toFixed(2)}%`}
function resetBrowse(){visibleLimit=70;render()}
function priceFor(x){let p=priceMap.get(norm(x.title));if(p)return p;for(const a of aliasesById.get(x.id)||[]){p=priceMap.get(a);if(p)return p}return null}
function money(v){return v==null?'—':`$${Number(v).toFixed(2)}`}
function priceHtml(x){const p=priceFor(x);if(!p)return `<div class="dossier-block"><h4>PRICE GUIDE</h4><p class="muted">No verified price profile yet.</p></div>`;return `<div class="dossier-block"><h4>PRICE GUIDE</h4><div class="hltb-times"><div><small>STRONG BUY</small><b>${money(p.s)}</b></div><div><small>TARGET</small><b>${money(p.g)}</b></div><div><small>CIB MARKET</small><b>${money(p.m)}</b></div></div></div>`}
function render(){let q=norm($("#q").value),all=[];for(const x of items){if(q&&!x.search.includes(q))continue;let st=effectiveStatus(x);if(filter!=="ALL"&&st!==filter)continue;all.push(x)}let rows=all.slice(0,visibleLimit),cards=rows.map(x=>{let c=collectionInfo(x),st=effectiveStatus(x),label=c?(c.owned?"OWNED · COLLECTION":"NEEDED · COLLECTION"):st,sub=c?`${c.owned?"On your shelf · ":""}Satisfies ${c.covered.length} game identities`:st==="OWNED"?"On your shelf":x.set==="EXCLUDED"?"Outside Josh Set":"Tap for details",click=c?`detailProduct('${c.product.key.replace(/'/g,"\\'")}')`:`detail(${x.id})`;return `<article class="card" onclick="${click}"><div class="top"><b>${esc(x.title)}</b><span class="badge ${st}">${label}</span></div><div class="sub">${sub}</div></article>`}).join("");let more=all.length>rows.length?`<button id="loadMore" style="width:100%;margin:14px 0;padding:14px">LOAD MORE · ${rows.length} / ${all.length}</button>`:all.length?`<p class="muted" style="text-align:center">Showing all ${all.length} results.</p>`:"";$("#results").innerHTML=cards+more||'<p class="muted">Nothing matched.</p>';let b=$("#loadMore");if(b)b.onclick=()=>{visibleLimit+=100;render()}}
function detailProduct(key){let p=productMap.get(key);if(!p)return;let covered=[...new Set(p.ids)].map(id=>byId.get(id)).filter(g=>g?.set==="INCLUDED"),owned=productSet.has(p.key);$("#detail").innerHTML=`<h2>${esc(p.title)}</h2><span class="badge ${owned?"OWNED":"NEEDED"}">${owned?"OWNED · COLLECTION":"NEEDED · COLLECTION"}</span><p>${owned?"This physical collection is on your shelf and covers the games below.":"Buying this physical collection satisfies the games below. The box itself is not an extra identity."}</p><h3>Satisfies ${covered.length} identities</h3><ul class="products">${covered.map(g=>`<li><b>${esc(g.title)}</b> · <span class="badge ${status(g)}">${status(g)}</span></li>`).join("")}</ul>`;dlg.showModal()}
function advice(x,p){if(status(x)==="OWNED")return["SKIP","Already owned."];if(x.set!=="INCLUDED")return["SKIP","Not part of the Josh Set."];const pr=priceFor(x),strong=pr?.s??x.strong,target=pr?.g??x.target,max=pr?.x??x.max;if(strong!=null&&p<=strong)return["GRAB IT",`At/below your ${money(strong)} strong-buy price.`];if(target!=null&&p<=target)return["BUY",`Within your ${money(target)} target.`];if(max!=null&&p<=max)return["FAIR",`Reasonable versus the ${money(max)} CIB market ceiling.`];if(max!=null)return["WAIT",`Above the ${money(max)} CIB market ceiling.`];return["NEED IT","You need it; no verified price profile yet."]}
function detail(id){let x=byId.get(id),c=collectionInfo(x),st=effectiveStatus(x),products=[...new Set(reverseProducts.get(id)||[])];if(c){detailProduct(c.product.key);return}$("#detail").innerHTML=`<h2>${esc(x.title)}</h2><span class="badge ${st}">${st}</span>${products.length?`<h3>Physical ways to satisfy it</h3><ul class="products">${products.slice(0,12).map(p=>`<li>${esc(p)}</li>`).join("")}</ul>`:""}${st==="NEEDED"?`${priceHtml(x)}<h3>Store Mode</h3><div class="price"><input id="ask" type="number" inputmode="decimal" min="0" step=".01" placeholder="Price"><button onclick="check(${id})">SHOULD I BUY IT?</button></div><div id="v"></div>`:""}`;dlg.showModal()}
function check(id){let p=Number($("#ask").value);if(!Number.isFinite(p))return;let[v,e]=advice(byId.get(id),p);$("#v").innerHTML=`<div class="verdict"><b>${v}</b><br>${esc(e)}</div>`}
async function importPrices(f){try{const d=JSON.parse(await f.text());if(!Array.isArray(d.prices))throw 0;const s={...stateCache,version:11,prices:d.prices,priceSource:d.source||f.name};saveState(s);resetBrowse();$("#syncmsg").textContent=`Prices: ${d.prices.length} verified CIB profiles loaded locally.`}catch{$("#syncmsg").textContent="Invalid ShelfCheck price profile."}}
const suffixes=["the fire fades edition","ancestral edition","return to castlevania edition","definitive edition","collector s edition","collectors edition","deluxe edition","complete edition","game of the year edition","goty edition"];
function candidates(t){let a=[];const add=v=>{let n=norm(v);if(n&&!a.includes(n))a.push(n)};add(t);let nb=t.replace(/\s*\[[^\]]+\]\s*$/,"").trim();if(nb!==t)add(nb);for(let seed of[...a])for(let s of suffixes)if(seed.endsWith(" "+s)){let b=seed.slice(0,-s.length-1).trim();if(b&&!a.includes(b))a.push(b)}return a}
function parseCSV(text){let rows=[],row=[],cell="",q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===","&&!q){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
async function importCSV(f){let rows=parseCSV(await f.text()),h=rows.shift()||[],ix=Object.fromEntries(h.map((x,i)=>[x,i])),owned=new Set(),ownedProducts=new Set(),titles=0,excluded=0,unmatched=[];for(let r of rows){let platform=(r[ix.Platform]||"").trim().toLowerCase(),cat=(r[ix.Category]||"").trim().toLowerCase(),typ=(r[ix.UserRecordType]||"Owned").trim().toLowerCase();if(!["sony playstation 4","playstation 4","ps4"].includes(platform)||cat!=="games"||typ!=="owned")continue;titles++;let title=r[ix.Title]||"",cs=candidates(title),hit=false;for(let c of cs){let p=productMap.get(c)||productMap.get(c.startsWith("the ")?c.slice(4):"the "+c);if(p){p.ids.forEach(id=>owned.add(id));ownedProducts.add(p.key);hit=true;break}}if(!hit)for(let c of cs){let ids=items.filter(x=>x.set==="INCLUDED"&&(norm(x.title)===c||(aliasesById.get(x.id)||[]).includes(c))).map(x=>x.id);if(ids.length){owned.add(ids[0]);hit=true;break}}if(!hit){let isExcluded=cs.some(c=>items.some(x=>x.set==="EXCLUDED"&&(norm(x.title)===c||(aliasesById.get(x.id)||[]).includes(c))));if(isExcluded){excluded++;hit=true}}if(!hit)unmatched.push(title)}saveState({...stateCache,version:11,owned:[...owned],products:[...ownedProducts],source:f.name});progress();resetBrowse();$("#syncmsg").textContent=`GameEye: ${titles} PS4 rows → ${owned.size} satisfied · ${ownedProducts.size} collection products · ${excluded} excluded · ${unmatched.length} unresolved.`;if(unmatched.length)console.warn("Unmatched",unmatched)}
function init(){progress();render();$("#q").oninput=resetBrowse;document.querySelector("nav").onclick=e=>{if(!e.target.dataset.s)return;filter=e.target.dataset.s;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b===e.target));resetBrowse()};$("#csv").onchange=e=>{let f=e.target.files[0];if(f)importCSV(f)};$("#priceBtn").onclick=()=>$("#prices").click();$("#prices").onchange=e=>{let f=e.target.files[0];if(f)importPrices(f)};$("#backup").onclick=()=>{let b=new Blob([JSON.stringify(stateCache,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="shelfcheck-backup.json";a.click();URL.revokeObjectURL(a.href)};$("#restoreBtn").onclick=()=>$("#restore").click();$("#restore").onchange=async e=>{try{let s=JSON.parse(await e.target.files[0].text());if(!Array.isArray(s.owned))throw 0;if(!Array.isArray(s.products))s.products=[];if(!Array.isArray(s.prices))s.prices=[];saveState(s);progress();resetBrowse();$("#syncmsg").textContent="Backup restored."}catch{$("#syncmsg").textContent="Invalid backup."}}}
loadData().catch(e=>{$("#results").innerHTML='<p class="muted">Could not load census data. Refresh once while online.</p>';console.error(e)});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));