let DATA,byId=new Map(),filter="ALL";const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const norm=s=>String(s??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replaceAll("&"," and ").match(/[a-z0-9]+/g)?.join(" ")||"";
function saved(){try{return JSON.parse(localStorage.getItem("joshSetState"))||null}catch{return null}}function save(x){localStorage.setItem("joshSetState",JSON.stringify(x))}
function state(){let s=saved();if(!s){let owned=DATA.identities.filter(x=>x.status==="OWNED").map(x=>x.identity_id);s={version:"0.7",owned,updated:new Date().toISOString()};save(s)}return s}
function status(x){if(x.set_status!=="INCLUDED")return x.set_status;return state().owned.includes(x.identity_id)?"OWNED":"NEEDED"}
function progress(){let n=state().owned.filter(id=>byId.get(id)?.set_status==="INCLUDED").length;$("#progress").textContent=`${n} / ${DATA.baseline.included} · ${(n/DATA.baseline.included*100).toFixed(2)}%`}
function render(){let q=norm($("#q").value);let rows=DATA.identities.filter(x=>(!q||norm(x.canonical_title).includes(q)||x.aliases.some(a=>norm(a).includes(q)))&&(filter==="ALL"||status(x)===filter)).slice(0,60);$("#results").innerHTML=rows.map(x=>`<article class="card" onclick="detail(${x.identity_id})"><div class="top"><b>${esc(x.canonical_title)}</b><span class="badge ${status(x)}">${status(x)}</span></div><div class="sub">${status(x)==="OWNED"?(x.satisfied_by_product?`Satisfied by ${esc(x.satisfied_by_product)}`:"On your shelf"):x.set_status==="EXCLUDED"?"Outside Josh Set":"Tap for details"}</div></article>`).join("")||'<p class="muted">Nothing matched.</p>'}
function advice(x,p){if(status(x)==="OWNED")return["SKIP","Already owned."];let s=x.strong_buy_price,t=x.target_price,m=x.max_reasonable_price,market=x.price?.cib_price;if(s!=null&&p<=s)return["GRAB IT",`At/below your $${s} strong-buy price.`];if(t!=null&&p<=t)return["BUY",`Within your $${t} target.`];if(m!=null&&p<=m)return["FAIR",`Reasonable, but not your target price.`];if(m!=null)return["WAIT",`Above your $${m} max-reasonable price.`];if(market!=null){if(p<=market*.75)return["GRAB IT",`Well under stored CIB reference ($${market}).`];if(p<=market*1.05)return["FAIR",`Near stored CIB reference ($${market}).`];return["WAIT",`Above stored CIB reference ($${market}).`]}return["NEED IT","Needed, but no price profile yet."]}
function detail(id){let x=byId.get(id),st=status(x);$("#detail").innerHTML=`<h2>${esc(x.canonical_title)}</h2><span class="badge ${st}">${st}</span>${x.gameplay_summary?`<p>${esc(x.gameplay_summary)}</p>`:""}${x.josh_fit_reason?`<p><b>Josh fit:</b> ${esc(x.josh_fit_reason)}</p>`:""}${x.products.length?`<h3>Physical ways to satisfy it</h3><ul class="products">${x.products.map(p=>`<li>${esc(p.display_title)}${p.region?` · ${esc(p.region)}`:""}</li>`).join("")}</ul>`:""}${st==="NEEDED"?`<h3>Store Mode</h3><div class="price"><input id="ask" type="number" inputmode="decimal" min="0" step=".01" placeholder="Price"><button onclick="check(${id})">SHOULD I BUY IT?</button></div><div id="v"></div>`:""}`;dlg.showModal()}
function check(id){let p=Number($("#ask").value);if(!Number.isFinite(p))return;let [v,e]=advice(byId.get(id),p);$("#v").innerHTML=`<div class="verdict"><b>${v}</b><br>${esc(e)}</div>`}
const suffixes=["the fire fades edition","ancestral edition","return to castlevania edition","definitive edition","collector s edition","collectors edition","deluxe edition","complete edition","game of the year edition","goty edition"];
function candidates(t){let a=[norm(t.replace(/\s*\[[^\]]+\]\s*$/,"") )],n=norm(t);if(!a.includes(n))a.unshift(n);for(let x of [...a])for(let s of suffixes)if(x.endsWith(" "+s))a.push(x.slice(0,-s.length-1).trim());return [...new Set(a)]}
function parseCSV(text){let rows=[],row=[],cell="",q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c=='"'){if(q&&text[i+1]=='"'){cell+='"';i++}else q=!q}else if(c===","&&!q){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
$("#csv").onchange=async e=>{let f=e.target.files[0];if(!f)return;let rows=parseCSV(await f.text()),h=rows.shift(),ix=Object.fromEntries(h.map((x,i)=>[x,i])),owned=new Set(),titles=0,unmatched=[];for(let r of rows){let platform=(r[ix.Platform]||"").toLowerCase(),cat=(r[ix.Category]||"").toLowerCase(),typ=(r[ix.UserRecordType]||"Owned").toLowerCase();if(!["sony playstation 4","playstation 4","ps4"].includes(platform)||cat!=="games"||typ!=="owned")continue;titles++;let title=r[ix.Title]||"",hit=false;let cs=candidates(title);for(let c of cs){let ps=DATA.productLookup[c];if(ps){ps.forEach(id=>owned.add(id));hit=true;break}}if(!hit)for(let c of cs){let ids=[...new Set((DATA.lookup[c]||[]).filter(id=>byId.get(id)?.set_status==="INCLUDED"))];if(ids.length){owned.add(ids[0]);hit=true;break}}if(!hit&&cs.some(c=>DATA.excludedLookup[c]))hit=true;if(!hit)unmatched.push(title)}save({version:"0.7",owned:[...owned],updated:new Date().toISOString(),source:f.name});progress();render();$("#syncmsg").textContent=`GameEye synced: ${titles} PS4 rows → ${owned.size} satisfied identities${unmatched.length?` · ${unmatched.length} unmatched`:" · 0 unmatched"}.`}
$("#backup").onclick=()=>{let b=new Blob([JSON.stringify(state(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="josh-set-backup.json";a.click();URL.revokeObjectURL(a.href)}
$("#restoreBtn").onclick=()=>$("#restore").click();$("#restore").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let s=JSON.parse(await f.text());if(!Array.isArray(s.owned))throw 0;save(s);progress();render();$("#syncmsg").textContent="Backup restored."}catch{$("#syncmsg").textContent="That backup file is not valid."}}
$("#q").oninput=render;document.querySelector("nav").onclick=e=>{if(!e.target.dataset.s)return;filter=e.target.dataset.s;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b===e.target));render()}
fetch("data.json").then(r=>r.json()).then(d=>{DATA=d;d.identities.forEach(x=>byId.set(x.identity_id,x));progress();render()});
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");