// ShelfCheck census cleanup — explicit, auditable identity exclusions.
(()=>{
  const EXCLUDE=new Map([
    ['end of zoe','DLC / add-on for Resident Evil 7; not a standalone game identity.'],
    ['resident evil 7 biohazard end of zoe','DLC / add-on for Resident Evil 7; not a standalone game identity.'],
    ['the forge','DLC / add-on for Shadow of the Tomb Raider; not a standalone game identity.'],
    ['cities skylines parklife','Expansion/add-on for Cities: Skylines; full base game required.'],
    ['one punch man a hero nobody knows suiryu','DLC/add-on character content.'],
    ['diablo iii eternal collection','Physical edition/product of Diablo III: Ultimate Evil Edition; not a second playable identity.'],
    ['just cause 3 xl edition','Content/edition package of Just Cause 3; not a second playable identity.'],
    ['final fantasy xiv online the complete edition','Bundle/product for Final Fantasy XIV; not a distinct playable identity.'],
    ['final fantasy xiv online the complete experience','Bundle/product for Final Fantasy XIV; not a distinct playable identity.'],
    ['final fantasy xiv heavensward','Expansion for Final Fantasy XIV; not a standalone game identity.'],
    ['final fantasy xiv shadowbringers','Expansion for Final Fantasy XIV; not a standalone game identity.'],
    ['final fantasy xiv stormblood','Expansion for Final Fantasy XIV; not a standalone game identity.'],
    ['final fantasy xv royal edition','Content/edition package of Final Fantasy XV; not a second playable identity.'],
    ['xcom 2 collection','Collection/content edition of XCOM 2; not a second playable identity.'],
    ['warriors orochi 4 ultimate','Ultimate content edition of Warriors Orochi 4; not a second playable identity.'],
    ['velocity 2x critical mass edition','Edition/package variant of Velocity 2X.'],
    ['tropico 5 complete collection','Complete/content edition of Tropico 5.'],
    ['sudden strike 4 complete collection','Complete/content edition of Sudden Strike 4; retain as a physical product.'],
    ['railway empire complete collection','Complete/content edition of Railway Empire.'],
    ['mercenary kings reloaded edition','Reloaded content edition of Mercenary Kings.'],
    ['layers of fear masterpiece edition','Content edition of Layers of Fear.'],
    ['hollow knight voidheart edition','Content edition of Hollow Knight.'],
    ['hitman definitive edition','Content edition of Hitman.'],
    ['harvest moon light of hope special edition complete','Complete/content edition of Harvest Moon: Light of Hope.'],
    ['dungeons 3 complete collection','Complete/content edition of Dungeons 3.'],
    ['everspace stellar edition','Content edition of EVERSPACE.'],
    ['bomber crew complete edition','Complete/content edition of Bomber Crew.'],
    ['blood bowl 2 legendary edition','Content edition of Blood Bowl 2.'],
    ['cities skylines premium edition','Content/edition package of Cities: Skylines.'],
    ['minecraft story mode a telltale games series the complete adventure','Complete physical product of Minecraft: Story Mode; not a second identity.'],
    ['naruto shippuden ultimate ninja storm 4 road to boruto','Content edition of Naruto Shippuden: Ultimate Ninja Storm 4.'],
    ['mortal kombat 11 aftermath','Aftermath by itself is DLC, not a standalone game identity.'],
    ['rigs mechanized combat league','PSVR required.'],['robinson the journey','PSVR required.'],['starblood arena','PSVR required.'],['smash hit plunder','PSVR required.'],['moss','PSVR required on PS4.'],['doctor who the edge of time','PSVR required on PS4.'],['astro bot rescue mission','PSVR required on PS4.'],['loading human chapter 1','PSVR required on PS4.'],['ghost giant','PSVR required on PS4.'],['pixel ripped 1989','PSVR required on PS4.'],['red matter','PSVR required on PS4.'],['paper beast','PSVR required on PS4.'],['operation warcade','PSVR required on PS4.'],['radial g racing revolved','PSVR required on PS4.'],['rush vr','PSVR required on PS4.'],['the playroom vr','PSVR required on PS4.'],
    ['here they lie','Physical first pressing is PSVR-required; non-VR play requires patch.'],['light tracer','Physical PS4 release is VR-branded; no disc-level proof of qualifying non-VR build.'],
    ['rocket arena','Required online service permanently shut down.'],['lawbreakers','Required online servers permanently shut down.'],['battleborn','Required servers permanently shut down.'],['overwatch','Original service shut down/replaced; disc no longer preserves original identity.'],
    ['f1 2015','Serialized annual sports release excluded.'],['f1 2016','Serialized annual sports release excluded.'],['f1 2017','Serialized annual sports release excluded.'],['f1 2018','Serialized annual sports release excluded.'],['f1 2019','Serialized annual sports release excluded.'],['f1 2020','Serialized annual sports release excluded.'],
    ['after the fall','PSVR required; no non-VR mode exists on PS4.'],['project lux','PSVR required; no non-VR mode exists.'],['to the top','PSVR required; Limited Run Games released it under its dedicated VR series (spine LR-VR02) and no flatscreen mode was found.'],['let it die','Free-to-play digital-only game; no physical PS4 disc was ever released.'],['iro hero','Confirmed digital-only PS4 release; no physical edition exists for any region.'],['jet kave adventure','PS4 release is digital-only; the only boxed physical edition (Strictly Limited Games) is Nintendo Switch-exclusive.'],['the escapists','No physical PS4 release exists for this identity; only the sequel, The Escapists 2, received a physical PS4 release, in Europe.'],
    ['i ai','No physical PS4 release or compilation coverage was found; digital-only PlayStation Store listing.'],['back in 1995','PS4 release is digital-only (Cross-Buy with PS Vita); only the PS Vita version received a physical edition.'],['drainus','No PS4 release confirmed on any platform, physical or digital; only PC and Nintendo Switch releases were found.'],['dead island retro revenge','Only the base Dead Island Definitive Edition is on the PS4 Definitive Collection disc; Retro Revenge requires a separate download, same as Riptide, and does not qualify as an on-disc identity.'],['wonder boy returns remix','Distinct identity from Wonder Boy Returns (which has its own qualifying 2019 PS4 physical); Remix’s only physical release (Strictly Limited Games) is Nintendo Switch-exclusive.'],
    ['funko fusion','PS4 release is digital-only; physical editions were produced only for PS5, Xbox Series, and Nintendo Switch.'],['mr driller drillland','The 2021 PS4/PS5 remaster was published by Bandai Namco as a digital-only release; no physical PS4 edition was found in any region.'],['teki paki','Confirmed as free downloadable content bundled digitally with the Flying Fire Shark/Toaplan Arcade Garage compilations rather than shipped as on-disc content; no standalone physical release exists.'],['eldest souls','No evidence of a physical PS4 edition was found; retailer listings show the game distributed only through the PlayStation Store with no boxed retail release.'],['snk vs capcom svc chaos','On PS4 this exists only as Hamster’s digital-only ACA NEOGEO release; no physical PS4 disc edition of this identity exists.'],['tales of the tiny planet','PS4 release appears to be digital-only; only digital storefront listings were found with no retailer or publisher physical evidence.'],['ultra street fighter iv','The PS4 port was released digitally only on May 26, 2015 by Other Ocean Interactive; no standalone physical PS4 disc exists.'],['way of redemption','PS4 release is digital-only; search results returned exclusively digital storefront listings with no physical retail or publisher evidence found.'],['hustle kings','The PS4 version released as a free-to-play digital-only title; no evidence of a physical PS4 edition was found for this platform (unlike PS3/Vita/PSVR).'],['saga frontier remastered','Square Enix and Play-Asia confirmed the planned Asian physical PS4 release was cancelled prior to launch, with refunds issued; only the Nintendo Switch version received a physical edition.']
  ]);
  const KEEP=new Map([
    ['rocksmith 2014 edition','Peripheral dependency is not an exclusion.'],['rocksmith 2014 edition remastered','Peripheral dependency is not an exclusion.'],['surf world series','Standalone non-annual arcade sports game.'],['super blood hockey','Standalone non-annual arcade sports identity.'],['surgeon simulator anniversary edition','Standard PS4 play is not VR-required.'],['rez infinite','PSVR optional.'],['resident evil 7 biohazard','PSVR optional.'],['megadimension neptunia viir','VR interactions optional.'],['heavy fire red shadow','VR optional.'],['dont knock twice','VR optional.'],['the assembly','VR compatible rather than required.'],['hidden agenda','Companion-phone dependency is preservation metadata.'],['hitman 2','Online limitations do not erase identity.'],['hunt showdown','Online dependence tracked as preservation metadata.'],['dayz','Online dependence tracked as preservation metadata.'],['dead by daylight','Online dependence tracked as preservation metadata.'],['dead alliance','Service condition does not erase physical identity.'],['dissidia final fantasy nt','Online limitations do not erase identity.'],
    ['metal gear solid v the definitive experience','Verified physical package; Ground Zeroes and The Phantom Pain on disc.'],['metal slug anthology','Verified qualifying physical compilation.'],['monster hunter world iceborne','Keep identity; Master Edition is preferred product.'],['monster hunter world iceborne master edition','Verified package containing World plus Iceborne.'],['mortal kombat 11 aftermath kollection','Verified physical package; track as product.'],['the banner saga trilogy','Verified compilation with all three games on disc.'],['bioshock the collection','Verified two-disc compilation.'],['uncharted the nathan drake collection','Verified compilation.'],['marvel vs capcom fighting collection arcade classics','Verified physical compilation.'],['capcom fighting collection 2','Verified physical compilation.'],['aleste collection','Verified physical compilation.'],['pinball arcade','Qualifying physical release.'],['talisman digital edition 40th anniversary collection','Playable physical release.'],['remothered tormented fathers broken porcelain double pack','Verified two-disc double pack.'],['crysis remastered trilogy','Verified trilogy on disc.'],['trine ultimate collection','Verified collection.'],['crash bandicoot n sane trilogy','Physical release contains three remade campaigns.'],['tales from the borderlands','Physical release contains full episodic game.'],['doom slayers collection','Only qualifying disc coverage counts; codes do not.'],
    ['last labyrinth','Originally PSVR-required, but the March 2023 Lucidity Lost update added a PS4 monitor mode playable without a headset.'],['umbrella corps','Confirmed offline single-player content exists (about 20 solo missions); uses P2P hosting rather than dedicated servers.'],['verdun','No traditional single-player campaign, but a confirmed offline bot mode (Squad Defence) is playable with zero internet connection.'],['prototype','Confirmed physical PS4 release via Prototype: Biohazard Bundle (Activision, October 2016), containing Prototype and Prototype 2.'],['the walking dead michonne a telltale miniseries','Confirmed physical coverage via The Walking Dead: The Telltale Definitive Series compilation disc.'],['jinki resurrection','Confirmed region-free physical PS4 release (Entergram); Japanese-only text does not disqualify an import, though lack of English is a genuine buying consideration.'],
    ['project starship','Confirmed standalone physical PS4 disc (Red Art Games, boxed with manual), distinct from the sequel Project Starship X.'],['damsel','Confirmed physical PS4 edition (eastasiasoft).'],['legend of the skyfish','Confirmed PS4-specific physical product (Red Art Games), in addition to its Switch release.'],['shantae','Confirmed physical PS4 release: Limited Run Games #468 Collector’s Edition.']
  ]);
  registerCensusMutation('exclude',()=>{const changed=[],kept=[];for(const x of items){const key=norm(x.title),reason=EXCLUDE.get(key),keep=KEEP.get(key);if(reason&&x.set==='INCLUDED'){x.set='EXCLUDED';x.cleanupReason=reason;changed.push(x.title);}else if(keep&&x.set==='INCLUDED'){x.cleanupReviewed=true;x.cleanupReason=keep;kept.push(x.title);}}console.log(`ShelfCheck census cleanup: ${changed.length} newly excluded; ${kept.length} reviewed/kept`,{excluded:changed,kept});});
})();