let DOSSIERS=new Map(),dossiersReady=false,HLTB=new Map(),hltbReady=false,DOSSIER_AUDIT={good:0,thin:0,generic:0,missing:0,badSummary:0};
const GENERIC_DOSSIER_PATTERNS=[/strongest constitutional role/i,/still needs curator review/i,/dossier establishes what the game is/i,/identity is preserved separately/i,/keep this identity in the census/i,/physical path should remain explicit/i,/collector relevance comes from/i,/this entry matters because it represents/i,/treat this as a distinct playable identity/i,/worth keeping visible in the set/i,/contributes to an established series or franchise/i,/no major concern was obvious from the introductory source/i,/redundancy and shelf representation still need review/i];
const BAD_SUMMARY_PATTERNS=[/\bis an (english|american|japanese|canadian|australian|british) (actor|actress|singer|writer|politician|footballer|athlete|musician)\b/i,/\bbest known for (playing|portraying|his|her)\b/i,/\bis the (son|daughter|wife|husband) of\b/i,/\bborn \d{1,2} [a-z]+ \d{4}\b/i];
function usefulText(v){if(!v)return'';const s=String(v).trim();if(s.length<28)return'';return GENERIC_DOSSIER_PATTERNS.some(r=>r.test(s))?'':s}
function titleTokens(title){return norm(title).split(/\s+/).filter(w=>w.length>2&&!['the','and','for','with','from','edition','complete','remastered','game'].includes(w))}
function summaryLooksWrong(d,x){const s=usefulText(d?.s);if(!s)return false;if(BAD_SUMMARY_PATTERNS.some(r=>r.test(s)))return true;const toks=titleTokens(x?.title||d?.t||'');if(toks.length>=2&&!toks.some(t=>norm(s).includes(t))&&/\b(actor|actress|singer|politician|footballer|television|tv series)\b/i.test(s))return true;return false}
function dossierQuality(d,x){if(!d)return{kind:'missing',score:0};const summaryBad=summaryLooksWrong(d,x),fields=[summaryBad?'':d.s,d.w,d.c,d.r,d.b].map(usefulText).filter(Boolean),words=fields.join(' ').split(/\s+/).filter(Boolean).length,score=fields.length*20+Math.min(20,Math.floor(words/8));if(summaryBad&&fields.length<2)return{kind:'badSummary',score:0};if(!fields.length)return{kind:'generic',score:0};if(fields.length<3||words<55||summaryBad)return{kind:'thin',score:Math.min(69,score)};return{kind:'good',score:Math.min(100,Math.max(70,score))}}
function auditDossiers(){DOSSIER_AUDIT={good:0,thin:0,generic:0,missing:0,badSummary:0};const queues={good:[],thin:[],generic:[],missing:[],badSummary:[]};for(const x of items){if(x.set!=='INCLUDED')continue;const d=dossierFor(x),q=dossierQuality(d,x);DOSSIER_AUDIT[q.kind]++;queues[q.kind].push(x.title)}const report={...DOSSIER_AUDIT,total:Object.values(DOSSIER_AUDIT).reduce((n,v)=>n+v,0),queues};window.SHELFCHECK_DOSSIER_AUDIT=report;let el=document.querySelector('#dossierAuditData');if(!el){el=document.createElement('script');el.id='dossierAuditData';el.type='application/json';document.body.appendChild(el)}el.textContent=JSON.stringify(report);console.log('ShelfCheck dossier audit',DOSSIER_AUDIT);return DOSSIER_AUDIT}
async function loadDossiers(){try{const r=await fetch('shelfcheck-dossiers.txt');if(!r.ok)throw Error('dossiers');const b64=(await r.text()).trim(),raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip')),rows=JSON.parse(await new Response(stream).text());for(const d of rows)DOSSIERS.set(norm(d.t),d);dossiersReady=true;auditDossiers();console.log(`ShelfCheck: ${rows.length} dossiers loaded`)}catch(e){console.warn('ShelfCheck dossiers unavailable',e)}}
async function loadHLTB(){try{const r=await fetch('hltb-data.txt');if(!r.ok)throw Error('hltb');const b64=(await r.text()).trim(),raw=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip')),rows=JSON.parse(await new Response(stream).text());for(const d of rows)HLTB.set(norm(d.t),d);hltbReady=true;console.log(`ShelfCheck: ${rows.length} HLTB records loaded`)}catch(e){console.warn('ShelfCheck HLTB unavailable',e)}}
function dossierFor(x){let d=DOSSIERS.get(norm(x.title));if(d)return d;for(const a of aliasesById.get(x.id)||[]){d=DOSSIERS.get(a);if(d)return d}return null}
function hltbFor(x){let d=HLTB.get(norm(x.title));if(d)return d;for(const a of aliasesById.get(x.id)||[]){d=HLTB.get(a);if(d)return d}return null}
function fmtHours(v){if(v==null||!Number.isFinite(Number(v)))return null;const n=Number(v);return `${Number.isInteger(n)?n:n.toFixed(1)}h`}
function hltbHtml(x){const h=hltbFor(x);if(!h)return `<div class="dossier-block"><h4>HOW LONG TO BEAT</h4><p class="muted">${hltbReady?'No verified HLTB timing for this identity.':'Loading playtime…'}</p></div>`;const vals=[['MAIN',h.a],['MAIN + EXTRA',h.e],['COMPLETIONIST',h.c]].map(([k,v])=>[k,fmtHours(v)]).filter(([,v])=>v);if(vals.length)return `<div class="dossier-block"><h4>HOW LONG TO BEAT</h4><div class="hltb-times">${vals.map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div></div>`;const notes={COMPILATION_COMPONENT_TIMES:'Compilation: use the individual game identities for playtimes.',NO_FIXED_HLTB_TIME:'No useful fixed completion time for this game.',CONTENT_OR_EDITION_REVIEW:'Content/edition timing is intentionally not treated as a separate game time.',JOSHSET_EXCLUDE_PSVR:'PSVR-required title — outside the Josh Set.',HLTB_NO_VERIFIED_MATCH:'No verified HLTB timing available.'};return `<div class="dossier-block"><h4>HOW LONG TO BEAT</h4><p class="muted">${esc(notes[h.q]||'No verified HLTB timing available.')}</p></div>`}
function dossierHtml(x){const d=dossierFor(x),q=dossierQuality(d,x);if(!d||q.kind==='generic'||q.kind==='badSummary')return `<section class="dossier"><div class="dossier-head"><div><small>THE JOSH SET</small><h3>JOSH DOSSIER</h3></div><span class="confidence">RESEARCH NEEDED</span></div>${hltbHtml(x)}${priceHtml(x)}<p class="muted">${dossiersReady?'The existing dossier failed validation, so ShelfCheck hid it rather than show generic or mismatched information.':'Loading dossier…'}</p></section>`;const section=(title,text)=>{const clean=usefulText(text);return clean?`<div class="dossier-block"><h4>${title}</h4><p>${esc(clean).replace(/\n/g,'<br>')}</p></div>`:''},badge=q.kind==='good'?(d.f?`${esc(d.f)}% CONF.`:'RESEARCHED'):'NEEDS ENRICHMENT',summary=summaryLooksWrong(d,x)?'':usefulText(d.s);return `<section class="dossier"><div class="dossier-head"><div><small>THE JOSH SET</small><h3>JOSH DOSSIER</h3></div><span class="confidence">${badge}</span></div>${d.d?`<div class="release">Released ${esc(d.d)}</div>`:''}${hltbHtml(x)}${priceHtml(x)}${summary?section('QUICK SUMMARY',summary):''}${section('WHY IT BELONGS',d.w)}${section('WATCH OUT FOR',d.c)}${section('JOSH / CURATOR TAKE',d.r)}${section('PHYSICAL / COVERAGE',d.b)}${usefulText(d.p)?`<div class="recommendation"><small>RECOMMENDATION</small><b>${esc(d.p)}</b></div>`:''}</section>`}
function storeFacts(x){const h=hltbFor(x),d=dossierFor(x),pr=priceFor(x),pref=preferredCollectionFor(x);let time=null;if(h){time=fmtHours(h.a)||fmtHours(h.e)||fmtHours(h.c)}return{h,d,pr,pref,time}}
function storeModeHtml(x){const f=storeFacts(x),bits=[];if(f.pr)bits.push(`CIB ${money(f.pr.m)}`);if(f.time)bits.push(`~${f.time} main`);if(f.pref)bits.push(`Collection option: ${f.pref.p.title} (${f.pref.count} identities)`);return `<h3>Store Mode</h3>${bits.length?`<p class="muted">${bits.map(esc).join(' · ')}</p>`:''}<div class="price"><input id="ask" type="number" inputmode="decimal" min="0" step=".01" placeholder="Store price"><button onclick="check(${x.id})">SHOULD I BUY IT?</button></div><div id="v"></div>`}
function storeAdvice(x,p){if(status(x)==='OWNED')return['SKIP','Already owned.'];if(x.set!=='INCLUDED')return['SKIP','Outside the Josh Set.'];const f=storeFacts(x),strong=f.pr?.s??x.strong,target=f.pr?.g??x.target,max=f.pr?.x??x.max;let verdict='NEED IT',why='You need it; no verified price profile yet.';const fairCeiling=max!=null?Math.max(max*1.05,max+1):null;if(strong!=null&&p<=strong){verdict='GRAB IT';why=`${money(p)} is at/below the ${money(strong)} strong-buy price.`}else if(target!=null&&p<=target){verdict='BUY';why=`${money(p)} is within the ${money(target)} target.`}else if(fairCeiling!=null&&p<=fairCeiling){verdict='FAIR';why=p<=max?`${money(p)} is reasonable versus ${money(max)} CIB market.`:`${money(p)} is effectively market price (${money(max)} CIB); small store/rounding differences are within tolerance.`}else if(max!=null){verdict='WAIT';why=`${money(p)} is meaningfully above the ${money(max)} CIB market price.`}const notes=[];if(f.time)notes.push(`Main story about ${f.time}.`);if(f.d?.p&&dossierQuality(f.d,x).kind==='good')notes.push(`Dossier: ${f.d.p}.`);if(f.pref&&!f.pref.owned){notes.push(`Before buying the standalone copy, check ${f.pref.p.title}; it covers ${f.pref.count} Josh Set identities.`);if(verdict==='GRAB IT'||verdict==='BUY')verdict+=' · CHECK COLLECTION'}return[verdict,[why,...notes].join(' ')]}
function detail(id){const x=byId.get(id),c=collectionInfo(x),st=effectiveStatus(x),products=[...new Set(reverseProducts.get(id)||[])];let top='';if(c){top=`<h2>${esc(x.title)}</h2><span class="badge ${c.owned?'OWNED':'NEEDED'}">${c.owned?'OWNED · COLLECTION':'NEEDED · COLLECTION'}</span><p>${c.owned?'This physical collection is on your shelf and covers the games below.':'Buying this physical collection satisfies the games below. The box itself is not an extra identity.'}</p><h3>Satisfies ${c.covered.length} identities</h3><ul class="products">${c.covered.map(g=>`<li><b>${esc(g.title)}</b> · <span class="badge ${status(g)}">${status(g)}</span></li>`).join('')}</ul>`}else{top=`<h2>${esc(x.title)}</h2><span class="badge ${st}">${st}</span>${products.length?`<h3>Physical ways to satisfy it</h3><ul class="products">${products.slice(0,12).map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`:''}${st==='NEEDED'?storeModeHtml(x):''}`};const paint=()=>{$('#detail').innerHTML=top+dossierHtml(x)};paint();dlg.showModal();if(!dossiersReady||!hltbReady)setTimeout(()=>{if(dlg.open)paint()},500)}
check=function(id){const el=$('#ask'),p=Number(el?.value);if(!el||el.value===''||!Number.isFinite(p))return;const[v,e]=storeAdvice(byId.get(id),p);$('#v').innerHTML=`<div class="verdict"><b>${esc(v)}</b><br>${esc(e)}</div>`}
loadDossiers();loadHLTB();
