// ShelfCheck model repair: physical products are not identities, and duplicate/variant
// product rows must be merged before deciding what a box satisfies.
let mergedProductIndex=null;
function productKeys(raw,title){const out=[];const add=v=>{const n=norm(v);if(n&&!out.includes(n))out.push(n);if(n.startsWith('the ')&&!out.includes(n.slice(4)))out.push(n.slice(4));};add(title||'');add(String(title||'').replace(/\s*\[[^\]]+\]\s*$/,'').trim());add(raw||'');return out}
function ensureMergedProducts(){if(mergedProductIndex||!DATA)return mergedProductIndex;const groups=new Map(),aliases=new Map();for(const [raw,title,ids] of DATA.p){const keys=productKeys(raw,title),canonical=keys.find(k=>!k.includes(' not for resale'))||keys[0];if(!canonical)continue;let g=groups.get(canonical);if(!g){g={key:canonical,title,ids:[],titles:[]};groups.set(canonical,g)}g.ids.push(...(ids||[]));g.titles.push(title);for(const k of keys)aliases.set(k,canonical)}for(const [raw,title] of DATA.p){const base=norm(String(title||'').replace(/\s*\[[^\]]+\]\s*$/,'').trim()),exact=norm(title||'');if(base&&exact!==base){const target=aliases.get(base)||base,source=aliases.get(exact);if(source&&source!==target&&groups.has(source)){let t=groups.get(target)||{key:target,title:String(title).replace(/\s*\[[^\]]+\]\s*$/,'').trim(),ids:[],titles:[]},s=groups.get(source);t.ids.push(...s.ids);t.titles.push(...s.titles);groups.set(target,t);groups.delete(source);for(const[k,v]of aliases)if(v===source)aliases.set(k,target)}aliases.set(exact,target);aliases.set(base,target)}}mergedProductIndex=new Map();for(const[key,g]of groups){g.ids=[...new Set(g.ids)];mergedProductIndex.set(key,g)}for(const[alias,key]of aliases)if(groups.has(key))mergedProductIndex.set(alias,groups.get(key));return mergedProductIndex}
function findProduct(title){const idx=ensureMergedProducts();if(!idx)return null;for(const k of productKeys('',title)){const p=idx.get(k);if(p)return p}return null}
function productCoverage(p){const covered=[...new Set(p.ids)].map(id=>byId.get(id)).filter(g=>g?.set==='INCLUDED'),missing=covered.filter(g=>status(g)==='NEEDED');return{covered,missing,owned:productSet.has(p.key)}}
function collectionInfo(x){const p=findProduct(x.title);if(!p)return null;const c=productCoverage(p);if(c.covered.length<2)return null;return{product:p,...c}}
function effectiveStatus(x){let c=collectionInfo(x);return c?(c.owned?'OWNED':status(x)):status(x)}
function acquisitionRank(x,q){const c=collectionInfo(x),st=effectiveStatus(x);if(c&&!c.owned&&c.missing.length)return 0;if(st==='NEEDED'&&x.set==='INCLUDED')return 1;if(c&&c.owned)return 2;if(st==='OWNED')return 3;return 4}
function preferredCollectionFor(x){const idx=ensureMergedProducts(),seen=new Set(),choices=[];for(const p of idx.values()){if(seen.has(p.key))continue;seen.add(p.key);const c=productCoverage(p);if(c.covered.length>1&&c.missing.length&&c.missing.some(g=>g.id===x.id))choices.push({p,count:c.covered.length,missing:c.missing.length,owned:c.owned})}choices.sort((a,b)=>(a.owned-b.owned)||(b.missing-a.missing)||(b.count-a.count)||a.p.title.localeCompare(b.p.title));return choices[0]||null}
// Search hardening: the plain substring check below (x.search.includes(q)) already handles
// punctuation differences, since both the query and every title/alias pass through the same
// norm() before comparison -- "dragon-ball"/"dragon.ball"/"dragon ball" all normalize to the
// identical "dragon ball" token string. The gap this closes is WHITESPACE the query omits
// that the target has ("dragonb" vs "dragon ball the breakers"), or a short connecting
// stopword the query skips ("princepersia" vs "prince of persia"). SEARCH_STOPWORDS is
// deliberately tiny (3 words, all 3+ letters -- single-letter words like "a"/"an" were
// deliberately excluded after testing showed they can bridge two unrelated words into an
// accidental match, e.g. stripping "a" from "Twin Breaker: A Sacred..." makes
// "breaker"+"sacred" spell "breakers") and the compact path only
// engages for queries of 5+ normalized characters, so short/ambiguous queries (the existing
// false-positive-guardrail cases: "dra","the","game","ball","ps","xx") are completely
// unaffected -- they still resolve through the exact same substring check as before.
const SEARCH_STOPWORDS=new Set(['the','of','and']);
function searchCompact(normalizedStr){return (normalizedStr||'').split(' ').filter(t=>t&&!SEARCH_STOPWORDS.has(t)).join('')}
function searchTextMatches(searchStr,q,qCompact){if(!q)return true;if(searchStr.includes(q))return true;if(qCompact.length>=5)return searchCompact(searchStr).includes(qCompact);return false}
function matchingCollectionProducts(q,qCompact){if(!q||filter==='EXCLUDED')return[];const idx=ensureMergedProducts(),seen=new Set(),out=[];for(const p of idx.values()){if(seen.has(p.key))continue;seen.add(p.key);const c=productCoverage(p);if(c.covered.length<2)continue;if(!c.owned&&!c.missing.length)continue;if(filter==='OWNED'&&!c.owned)continue;if(filter==='NEEDED'&&(c.owned||!c.missing.length))continue;if(!c.covered.some(x=>searchTextMatches(x.search,q,qCompact))&&!searchTextMatches(norm(p.title),q,qCompact))continue;out.push({p,...c});}return out.sort((a,b)=>(a.owned-b.owned)||(b.missing.length-a.missing.length)||(b.covered.length-a.covered.length)||a.p.title.localeCompare(b.p.title))}
function render(){const q=norm($('#q').value),qCompact=searchCompact(q);let all=items.filter(x=>{if(q&&!searchTextMatches(x.search,q,qCompact))return false;const st=effectiveStatus(x);if(filter==='EXCLUDED')return x.set==='EXCLUDED';if(filter==='ALL')return x.set!=='EXCLUDED';return x.set!=='EXCLUDED'&&st===filter;});if(window.SHELFCHECK_SORT==='ZA')all.sort((a,b)=>b.title.localeCompare(a.title,undefined,{sensitivity:'base',numeric:true}));else if((window.SHELFCHECK_SORT==='LOW'||window.SHELFCHECK_SORT==='HIGH')&&typeof window.SHELFCHECK_PRICE_COMPARE==='function')all.sort(window.SHELFCHECK_PRICE_COMPARE);else if(q)all.sort((a,b)=>acquisitionRank(a,q)-acquisitionRank(b,q)||a.title.localeCompare(b.title));const rows=all.slice(0,visibleLimit),products=matchingCollectionProducts(q,qCompact),shownProducts=new Set(products.map(c=>c.p.key));const productHtml=products.map(c=>{const gain=c.missing.length,total=c.covered.length,label=c.owned?'OWNED · COLLECTION':gain===total?'BEST WAY TO BUY':'COLLECTION OPTION',sub=c.owned?`On your shelf · Covers ${total} game identities`:`Adds ${gain} missing ${gain===1?'game':'games'} · ${total} total in box`;return `<article class="card"><div class="top"><b>${esc(c.p.title)}</b><span class="badge ${c.owned?'OWNED':'NEEDED'}">${label}</span></div><div class="sub">${sub}</div></article>`}).join('');const rowHtml=rows.filter(x=>{const c=collectionInfo(x);return !c||!shownProducts.has(c.product.key)}).map(x=>{const c=collectionInfo(x),st=effectiveStatus(x),pref=!c&&st==='NEEDED'?preferredCollectionFor(x):null;let label,sub;if(c){label=c.owned?'OWNED · COLLECTION':c.missing.length===c.covered.length?'BEST WAY TO BUY':'COLLECTION OPTION';sub=c.owned?`On your shelf · Covers ${c.covered.length} game identities`:`Adds ${c.missing.length} missing ${c.missing.length===1?'game':'games'} · ${c.covered.length} total in box`;}else{label=st;sub=st==='OWNED'?'On your shelf':x.set==='EXCLUDED'?'Outside Josh Set':pref?`Collection option: ${pref.p.title} · adds ${pref.missing}/${pref.count}`:'Tap for details';}return `<article class="card" onclick="detail(${x.id})"><div class="top"><b>${esc(x.title)}</b><span class="badge ${st}">${label}</span></div><div class="sub">${esc(sub)}</div></article>`}).join('');const more=all.length>rows.length?`<button id="loadMore" style="width:100%;margin:14px 0;padding:14px">LOAD MORE · ${rows.length} / ${all.length}</button>`:all.length?`<p class="muted" style="text-align:center">Showing all ${all.length} results.</p>`:'';const resultsHtml=productHtml+rowHtml+more;$('#results').innerHTML=resultsHtml||zeroResultHtml(q,qCompact);const b=$('#loadMore');if(b)b.onclick=()=>{visibleLimit+=100;render()};}
// Zero-result messaging: distinguishes "genuinely not in ShelfCheck" (the exact failure that
// let Dragon Ball: The Breakers stay silently absent) from "exists, but the current filter
// hides it" (e.g. searching an OWNED title while on the NEEDED tab). A blank search with an
// empty filtered list still gets the plain, unalarming "Nothing matched." -- this warning only
// fires for a non-empty search query.
function zeroResultHtml(q,qCompact){if(!q)return '<p class="muted">Nothing matched.</p>';const matched=items.filter(x=>searchTextMatches(x.search,q,qCompact));if(!matched.length)return `<div class="muted" style="text-align:center;padding:22px 14px"><p style="font-weight:700;margin:0 0 8px">⚠️ NOT FOUND IN SHELFCHECK</p><p style="margin:0 0 6px">No match for "${esc($('#q').value)}".</p><p style="margin:0">This does NOT mean you already own it or don't need it. Verify the title before buying.</p></div>`;const sample=matched.slice(0,3).map(x=>`${esc(x.title)} — ${effectiveStatus(x)}`).join('<br>');return `<div class="muted" style="text-align:center;padding:22px 14px"><p style="font-weight:700;margin:0 0 8px">Found in ShelfCheck, but not in the current filter.</p><p style="margin:0 0 10px">${sample}</p><button onclick="filter='ALL';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.s==='ALL'));resetBrowse()">SHOW ALL</button></div>`}
async function importCSV(f){const rows=parseCSV(await f.text()),h=rows.shift()||[],ix=Object.fromEntries(h.map((x,i)=>[x,i]));const owned=new Set(),ownedProducts=new Set(),unmatched=[];let titles=0,excluded=0;const idx=ensureMergedProducts();for(const r of rows){const platform=(r[ix.Platform]||'').trim().toLowerCase(),cat=(r[ix.Category]||'').trim().toLowerCase(),typ=(r[ix.UserRecordType]||'Owned').trim().toLowerCase();if(!['sony playstation 4','playstation 4','ps4'].includes(platform)||cat!=='games'||typ!=='owned')continue;titles++;const title=r[ix.Title]||'',cs=candidates(title);let hit=false;for(const c of cs){const keys=productKeys(c,c);let p=null;for(const k of keys){p=idx?.get(k);if(p)break}if(!p)continue;const includedIds=[...new Set(p.ids)].filter(id=>byId.get(id)?.set==='INCLUDED');if(includedIds.length){includedIds.forEach(id=>owned.add(id));ownedProducts.add(p.key);hit=true;break}}if(!hit)for(const c of cs){const ids=items.filter(x=>x.set==='INCLUDED'&&(norm(x.title)===c||(aliasesById.get(x.id)||[]).includes(c))).map(x=>x.id);if(ids.length){owned.add(ids[0]);hit=true;break}}if(!hit){const isExcluded=cs.some(c=>items.some(x=>x.set==='EXCLUDED'&&(norm(x.title)===c||(aliasesById.get(x.id)||[]).includes(c))));if(isExcluded){excluded++;hit=true}}if(!hit)unmatched.push(title)}saveState({...stateCache,version:11,owned:[...owned],products:[...ownedProducts],source:f.name});progress();resetBrowse();$('#syncmsg').textContent=`GameEye: ${titles} PS4 rows → ${[...owned].filter(id=>byId.get(id)?.set==='INCLUDED').length} satisfied · ${ownedProducts.size} collection products · ${excluded} excluded · ${unmatched.length} unresolved.`;if(unmatched.length)console.warn('Unmatched',unmatched);}