import fs from 'node:fs';import zlib from 'node:zlib';import vm from 'node:vm';
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'`]/g,'').replaceAll('&',' and ').match(/[a-z0-9]+/g)?.join(' ')||'';
const b64=['data0.txt','data1.txt','data2.txt','data3a.txt','data3b.txt'].map(x=>fs.readFileSync(x,'utf8')).join('').trim();
const DATA=JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'));let items=DATA.i.map(r=>({id:r[0],title:r[1],set:r[2],max:r[6],search:norm(r[1])})),byId=new Map(items.map(x=>[x.id,x]));
const ctx={DATA,items,byId,norm,window:{},console,setTimeout:(f)=>{f();return 1},clearTimeout:()=>{},setInterval:(f)=>{for(let i=0;i<8;i++)f();return 1},clearInterval:()=>{},progress:()=>{},resetBrowse:()=>{},stateCache:{owned:[],products:[],prices:[]},ownedSet:new Set(),productSet:new Set(),filter:'ALL',aliasesById:new Map(),productMap:new Map(),reverseProducts:new Map()};vm.createContext(ctx);
for(const f of ['census-cleanup.js','census-v034.js','census-collapse-v035.js','census-v035-final.js','census-v040-pricing-audit.js','census-v052-pricecharting-negative-space.js','census-v053-pricecharting-regional-sweep.js','census-v054-pricecharting-collection-gap.js','census-v055-pricecharting-ab-sweep.js','census-v056-pricecharting-cf-sweep.js','census-v057-pricecharting-gl-sweep.js','census-v058-pricecharting-mr-sweep.js','census-v059-pricecharting-sz-sweep.js','census-v060-integrity-scrub.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
items=ctx.items;const included=items.filter(x=>x.set==='INCLUDED');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function getRaw(url){for(let a=0;a<2;a++){try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}});const text=await r.text();return {ok:r.ok,status:r.status,url:r.url,text}}catch(e){if(a===1)return {ok:false,status:0,url,error:String(e),text:''};await sleep(300)}}}
async function get(url){const r=await getRaw(url);return r.ok?r.text:null}
const decode=s=>String(s??'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&#x27;/gi,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const HOSTS=['https://thecoverproject.net/','https://www.thecoverproject.net/','https://mobile.thecoverproject.net/','https://tan.thecoverproject.net/','https://formulario.thecoverproject.net/','https://about.thecoverproject.net/','https://www-.thecoverproject.net/'];
let BASE=null,best=-1;
for(const host of HOSTS){const r=await getRaw(host+'view.php?cat_id=60&view=g');const links=[...r.text.matchAll(/view\.php\?game_id=\d+/gi)].length;const challenge=/challenge screen|verify you are human|ddos|captcha|cloudflare/i.test(r.text);console.log('TCP PROBE',host,'status',r.status,'bytes',r.text.length,'gameLinks',links,'challenge',challenge,'final',r.url);if(r.ok&&links>best){best=links;BASE=host}}
if(!BASE||best<1)throw new Error('No Cover Project mirror exposed catalog HTML to GitHub runner');
console.log('TCP SELECTED',BASE,'sampleGameLinks',best);
const pages=[];for(const c of '#abcdefghijklmnopqrstuvwxyz')pages.push(BASE+'view.php?cat_id=60&view='+encodeURIComponent(c));
const index=new Map();
for(const url of pages){const h=await get(url);if(!h)continue;for(const m of h.matchAll(/href=["']([^"']*view\.php\?game_id=\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi)){const title=decode(m[2]).replace(/\s*\(\d+\)\s*$/,'').trim();if(title&&!index.has(norm(title)))index.set(norm(title),new URL(m[1],BASE).href)}}
console.log('Cover Project PS4 indexed titles',index.size);
function coverImage(h){const candidates=[];for(const m of h.matchAll(/<img[^>]+src=["']([^"']+)["'][^>]*>/gi)){const src=m[1];if(/cover|download|uploads|images/i.test(src))candidates.push(new URL(src,BASE).href)}for(const m of h.matchAll(/href=["']([^"']+\.(?:jpg|jpeg|png)(?:\?[^"']*)?)["']/gi))candidates.push(new URL(m[1],BASE).href);return candidates.find(u=>!/logo|button|icon|banner|blank/i.test(u))||null}
async function one(x){const page=index.get(norm(x.title));if(!page)return null;const h=await get(page);if(!h)return null;const img=coverImage(h);return img?{id:x.id,title:x.title,url:page,img}:null}
for(const title of ['Gravity Rush Remastered','Uncharted 4: A Thief\'s End']){const page=index.get(norm(title));console.log('cover smoke page',title,page||'MISS');if(!page)throw new Error('Cover Project catalog smoke test failed for '+title);const h=await get(page),img=h&&coverImage(h);console.log('cover smoke image',title,img||'MISS');if(!img)throw new Error('Cover Project image smoke test failed for '+title)}
const out=[];let cursor=0;const workers=Array.from({length:6},async()=>{while(true){const i=cursor++;if(i>=included.length)return;const x=included[i],r=await one(x);if(r)out.push(r);if(i%100===0)console.log(i,'/',included.length,'covers',out.length);await sleep(80)}});await Promise.all(workers);out.sort((a,b)=>a.id-b.id);
const obj=Object.fromEntries(out.map(x=>[x.id,x.img]));fs.writeFileSync('covers-manifest.js','// Generated by tools/fetch-covers.mjs from The Cover Project. Strict exact-title PS4 matches only.\nwindow.SHELFCHECK_COVERS='+JSON.stringify(obj)+';\nwindow.SHELFCHECK_COVER_META='+JSON.stringify({denominator:included.length,covers:out.length,pending:included.length-out.length,source:'The Cover Project',generated:new Date().toISOString()})+';\n');fs.writeFileSync('cover-audit.json',JSON.stringify({denominator:included.length,covers:out.length,pending:included.length-out.length,source:'The Cover Project',base:BASE,indexedTitles:index.size,rows:out},null,2));console.log(JSON.stringify({denominator:included.length,indexedTitles:index.size,covers:out.length,pending:included.length-out.length},null,2));