import fs from 'node:fs';import zlib from 'node:zlib';import vm from 'node:vm';
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'`]/g,'').replaceAll('&',' and ').match(/[a-z0-9]+/g)?.join(' ')||'';
const soft=s=>norm(s).replace(/\b(the|a|an|edition|remastered|collection|complete|game|games|series|playstation|ps4|trilogy|bundle|special)\b/g,' ').replace(/\s+/g,' ').trim();
const aliases=s=>{const n=norm(s),a=new Set([n,soft(s)]);a.add(n.replace(/\ba telltale games series\b/g,'').trim());a.add(n.replace(/\bthe telltale series\b/g,'').trim());a.add(n.replace(/\bchronicles trilogy\b/g,'chronicles'));a.add(n.replace(/\bcomplete edition\b/g,'').trim());a.add(n.replace(/\bday one edition\b/g,'').trim());a.add(n.replace(/\bbattle royal special\b/g,'').trim());a.add(n.replace(/\bspecial edition\b/g,'').trim());return [...a].filter(x=>x.length>2)};
const b64=['data0.txt','data1.txt','data2.txt','data3a.txt','data3b.txt'].map(x=>fs.readFileSync(x,'utf8')).join('').trim();const DATA=JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'));let items=DATA.i.map(r=>({id:r[0],title:r[1],set:r[2],max:r[6],search:norm(r[1])})),byId=new Map(items.map(x=>[x.id,x]));const ctx={DATA,items,byId,norm,window:{},console,setTimeout:(f)=>{f();return 1},clearTimeout:()=>{},setInterval:(f)=>{for(let i=0;i<8;i++)f();return 1},clearInterval:()=>{},progress:()=>{},resetBrowse:()=>{},stateCache:{owned:[],products:[],prices:[]},ownedSet:new Set(),productSet:new Set(),filter:'ALL',aliasesById:new Map(),productMap:new Map(),reverseProducts:new Map()};vm.createContext(ctx);for(const f of ['census-cleanup.js','census-v034.js','census-collapse-v035.js','census-v035-final.js','census-v040-pricing-audit.js','census-v052-pricecharting-negative-space.js','census-v053-pricecharting-regional-sweep.js','census-v054-pricecharting-collection-gap.js','census-v055-pricecharting-ab-sweep.js','census-v056-pricecharting-cf-sweep.js','census-v057-pricecharting-gl-sweep.js','census-v058-pricecharting-mr-sweep.js','census-v059-pricecharting-sz-sweep.js','census-v060-integrity-scrub.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});items=ctx.items;byId=ctx.byId;const included=items.filter(x=>x.set==='INCLUDED');
const productKeys=(raw,title)=>{const out=[];const add=v=>{const n=norm(v);if(n&&!out.includes(n))out.push(n);if(n.startsWith('the ')&&!out.includes(n.slice(4)))out.push(n.slice(4))};add(title||'');add(String(title||'').replace(/\s*\[[^\]]+\]\s*$/,'').trim());add(raw||'');return out};
function mergedProducts(){const groups=new Map(),alias=new Map();for(const [raw,title,ids] of DATA.p){const ks=productKeys(raw,title),key=ks.find(k=>!k.includes(' not for resale'))||ks[0];if(!key)continue;let g=groups.get(key);if(!g){g={key,title,ids:[],titles:[]};groups.set(key,g)}g.ids.push(...(ids||[]));g.titles.push(title);for(const k of ks)alias.set(k,key)}for(const [raw,title] of DATA.p){const base=norm(String(title||'').replace(/\s*\[[^\]]+\]\s*$/,'').trim()),exact=norm(title||'');if(base&&exact!==base){const target=alias.get(base)||base,source=alias.get(exact);if(source&&source!==target&&groups.has(source)){let t=groups.get(target)||{key:target,title:String(title).replace(/\s*\[[^\]]+\]\s*$/,'').trim(),ids:[],titles:[]},s=groups.get(source);t.ids.push(...s.ids);t.titles.push(...s.titles);groups.set(target,t);groups.delete(source);for(const[k,v]of alias)if(v===source)alias.set(k,target)}alias.set(exact,target);alias.set(base,target)}}return [...groups.values()].map(g=>({...g,ids:[...new Set(g.ids)]})).filter(g=>g.ids.filter(id=>byId.get(id)?.set==='INCLUDED').length>=2)}
const CLIENT_ID=process.env.IGDB_CLIENT_ID,SECRET=process.env.IGDB_CLIENT_SECRET;if(!CLIENT_ID||!SECRET)throw new Error('Missing IGDB credentials');const sleep=ms=>new Promise(r=>setTimeout(r,ms));const headers=token=>({'Client-ID':CLIENT_ID,'Authorization':'Bearer '+token,'Content-Type':'text/plain'});const tr=await fetch(`https://id.twitch.tv/oauth2/token?client_id=${encodeURIComponent(CLIENT_ID)}&client_secret=${encodeURIComponent(SECRET)}&grant_type=client_credentials`,{method:'POST'});if(!tr.ok)throw new Error('Twitch token '+tr.status);const {access_token:TOKEN}=await tr.json();console.log('IGDB auth OK; census',included.length);
async function post(endpoint,body){for(let a=0;a<4;a++){const r=await fetch('https://api.igdb.com/v4/'+endpoint,{method:'POST',headers:headers(TOKEN),body});if(r.ok)return await r.json();if(r.status===429){await sleep(1100);continue}throw new Error(endpoint+' '+r.status+' '+await r.text())}return[]}
async function search(q){const safe=q.replaceAll('\\','\\\\').replaceAll('"','\\"');return (await post('games',`search "${safe}"; fields id,name,cover.image_id,platforms,alternative_names.name; where platforms = (48); limit 50;`)).filter(x=>x.cover?.image_id)}
function keys(r){return new Set([norm(r.name),soft(r.name),...(r.alternative_names||[]).flatMap(a=>[norm(a.name),soft(a.name)])].filter(Boolean))}
function choose(title,rows){const wants=new Set(aliases(title));const scored=rows.map(r=>{const ks=keys(r);let score=0;if(ks.has(norm(title)))score=100;else if([...wants].some(w=>ks.has(w)))score=90;return{r,score}}).filter(x=>x.score>=90).sort((a,b)=>b.score-a.score);if(!scored.length)return null;const best=scored[0].score,top=scored.filter(x=>x.score===best);return top.length===1?{r:top[0].r,method:best===100?'exact':'igdb-alt'}:null}
function imageUrl(id){return `https://images.igdb.com/igdb/image/upload/t_cover_big/${id}.jpg`}
async function findCover(title){let hit=null;const qs=[title,...aliases(title)].filter((v,j,a)=>v&&a.indexOf(v)===j);for(const q of qs){const rows=await search(q);hit=choose(title,rows);if(hit)break;await sleep(270)}return hit}
let previous={},previousProducts={};try{const text=fs.readFileSync('covers-manifest.js','utf8'),m=text.match(/window\.SHELFCHECK_COVERS=(\{.*?\});\n/s),p=text.match(/window\.SHELFCHECK_PRODUCT_COVERS=(\{.*?\});\n/s);if(m)previous=JSON.parse(m[1]);if(p)previousProducts=JSON.parse(p[1])}catch{}
const out=[],recovered=[],still=[];for(let i=0;i<included.length;i++){const x=included[i];if(previous[x.id]){out.push({id:x.id,title:x.title,img:previous[x.id],method:'previous'});continue}const hit=await findCover(x.title);if(hit){const row={id:x.id,title:x.title,igdbName:hit.r.name,imageId:hit.r.cover.image_id,img:imageUrl(hit.r.cover.image_id),method:hit.method};out.push(row);recovered.push(row);console.log('RECOVER',x.title,'=>',hit.r.name,hit.method)}else still.push({id:x.id,title:x.title});await sleep(270)}
const products=mergedProducts(),productOut=[],productRecovered=[],productStill=[];console.log('Collection products to cover',products.length);for(const p of products){if(previousProducts[p.key]){productOut.push({key:p.key,title:p.title,img:previousProducts[p.key],method:'previous'});continue}const names=[p.title,...p.titles].filter((v,j,a)=>v&&a.indexOf(v)===j);let hit=null,used='';for(const name of names){hit=await findCover(name);if(hit){used=name;break}}if(hit){const row={key:p.key,title:p.title,query:used,igdbName:hit.r.name,imageId:hit.r.cover.image_id,img:imageUrl(hit.r.cover.image_id),method:hit.method};productOut.push(row);productRecovered.push(row);console.log('PRODUCT',p.title,'=>',hit.r.name,hit.method)}else productStill.push({key:p.key,title:p.title});await sleep(270)}
out.sort((a,b)=>a.id-b.id);const obj=Object.fromEntries(out.map(x=>[x.id,x.img])),pobj=Object.fromEntries(productOut.map(x=>[x.key,x.img]));const meta={denominator:included.length,covers:out.length,pending:included.length-out.length,recovered:recovered.length,products:products.length,productCovers:productOut.length,productPending:products.length-productOut.length,productRecovered:productRecovered.length,source:'IGDB',generated:new Date().toISOString()};fs.writeFileSync('covers-manifest.js','// Generated from IGDB. Exact + unique IGDB alternative-name recovery.\nwindow.SHELFCHECK_COVERS='+JSON.stringify(obj)+';\nwindow.SHELFCHECK_PRODUCT_COVERS='+JSON.stringify(pobj)+';\nwindow.SHELFCHECK_COVER_META='+JSON.stringify(meta)+';\n');fs.writeFileSync('cover-audit.json',JSON.stringify({...meta,recovered,still,productRecovered,productStill,rows:out,productRows:productOut},null,2));console.log(JSON.stringify(meta,null,2));