import fs from 'node:fs';import zlib from 'node:zlib';import vm from 'node:vm';
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'`]/g,'').replaceAll('&',' and ').match(/[a-z0-9]+/g)?.join(' ')||'';
const soft=s=>norm(s).replace(/\b(the|a|an|edition|remastered|collection|complete|game|games|series|playstation|ps4|trilogy|bundle)\b/g,' ').replace(/\s+/g,' ').trim();
const aliases=s=>{const n=norm(s),a=new Set([n,soft(s)]);a.add(n.replace(/\ba telltale games series\b/g,'').trim());a.add(n.replace(/\bthe telltale series\b/g,'').trim());a.add(n.replace(/\bchronicles trilogy\b/g,'chronicles'));a.add(n.replace(/\bcomplete edition\b/g,'').trim());a.add(n.replace(/\bday one edition\b/g,'').trim());return [...a].filter(x=>x.length>2)};
const b64=['data0.txt','data1.txt','data2.txt','data3a.txt','data3b.txt'].map(x=>fs.readFileSync(x,'utf8')).join('').trim();const DATA=JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'));let items=DATA.i.map(r=>({id:r[0],title:r[1],set:r[2],max:r[6],search:norm(r[1])})),byId=new Map(items.map(x=>[x.id,x]));const ctx={DATA,items,byId,norm,window:{},console,setTimeout:(f)=>{f();return 1},clearTimeout:()=>{},setInterval:(f)=>{for(let i=0;i<8;i++)f();return 1},clearInterval:()=>{},progress:()=>{},resetBrowse:()=>{},stateCache:{owned:[],products:[],prices:[]},ownedSet:new Set(),productSet:new Set(),filter:'ALL',aliasesById:new Map(),productMap:new Map(),reverseProducts:new Map()};vm.createContext(ctx);for(const f of ['census-cleanup.js','census-v034.js','census-collapse-v035.js','census-v035-final.js','census-v040-pricing-audit.js','census-v052-pricecharting-negative-space.js','census-v053-pricecharting-regional-sweep.js','census-v054-pricecharting-collection-gap.js','census-v055-pricecharting-ab-sweep.js','census-v056-pricecharting-cf-sweep.js','census-v057-pricecharting-gl-sweep.js','census-v058-pricecharting-mr-sweep.js','census-v059-pricecharting-sz-sweep.js','census-v060-integrity-scrub.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});items=ctx.items;const included=items.filter(x=>x.set==='INCLUDED');
const CLIENT_ID=process.env.IGDB_CLIENT_ID,SECRET=process.env.IGDB_CLIENT_SECRET;if(!CLIENT_ID||!SECRET)throw new Error('Missing IGDB credentials');const sleep=ms=>new Promise(r=>setTimeout(r,ms));const headers=token=>({'Client-ID':CLIENT_ID,'Authorization':'Bearer '+token,'Content-Type':'text/plain'});const tr=await fetch(`https://id.twitch.tv/oauth2/token?client_id=${encodeURIComponent(CLIENT_ID)}&client_secret=${encodeURIComponent(SECRET)}&grant_type=client_credentials`,{method:'POST'});if(!tr.ok)throw new Error('Twitch token '+tr.status);const {access_token:TOKEN}=await tr.json();console.log('IGDB auth OK; census',included.length);
async function post(endpoint,body){for(let a=0;a<4;a++){const r=await fetch('https://api.igdb.com/v4/'+endpoint,{method:'POST',headers:headers(TOKEN),body});if(r.ok)return await r.json();if(r.status===429){await sleep(1100);continue}throw new Error(endpoint+' '+r.status+' '+await r.text())}return[]}
async function search(q){const safe=q.replaceAll('\\','\\\\').replaceAll('"','\\"');return (await post('games',`search "${safe}"; fields id,name,cover.image_id,platforms,alternative_names.name; where platforms = (48); limit 50;`)).filter(x=>x.cover?.image_id)}
function keys(r){return new Set([norm(r.name),soft(r.name),...(r.alternative_names||[]).flatMap(a=>[norm(a.name),soft(a.name)])].filter(Boolean))}
function choose(title,rows){const wants=new Set(aliases(title));const scored=rows.map(r=>{const ks=keys(r);let score=0;if(ks.has(norm(title)))score=100;else if([...wants].some(w=>ks.has(w)))score=90;else{const t=soft(title);for(const k of ks){if(t.length>=8&&(k.includes(t)||t.includes(k)))score=Math.max(score,70)}}return{r,score}}).filter(x=>x.score>=90).sort((a,b)=>b.score-a.score);if(!scored.length)return null;const best=scored[0].score,top=scored.filter(x=>x.score===best);return top.length===1?{r:top[0].r,method:best===100?'exact':'igdb-alt'}:null}
function imageUrl(id){return `https://images.igdb.com/igdb/image/upload/t_cover_big/${id}.jpg`}
let previous={};try{const m=fs.readFileSync('covers-manifest.js','utf8').match(/window\.SHELFCHECK_COVERS=(\{.*?\});\n/s);if(m)previous=JSON.parse(m[1])}catch{}const out=[],recovered=[],still=[];for(let i=0;i<included.length;i++){const x=included[i];if(previous[x.id]){out.push({id:x.id,title:x.title,img:previous[x.id],method:'previous'});continue}let hit=null;const qs=[x.title,...aliases(x.title)].filter((v,j,a)=>v&&a.indexOf(v)===j);for(const q of qs){const rows=await search(q);hit=choose(x.title,rows);if(hit)break;await sleep(270)}if(hit){const row={id:x.id,title:x.title,igdbName:hit.r.name,imageId:hit.r.cover.image_id,img:imageUrl(hit.r.cover.image_id),method:hit.method};out.push(row);recovered.push(row);console.log('RECOVER',x.title,'=>',hit.r.name,hit.method)}else{still.push({id:x.id,title:x.title});console.log('STILL',x.title)}await sleep(270)}out.sort((a,b)=>a.id-b.id);const obj=Object.fromEntries(out.map(x=>[x.id,x.img]));const meta={denominator:included.length,covers:out.length,pending:included.length-out.length,recovered:recovered.length,source:'IGDB',generated:new Date().toISOString()};fs.writeFileSync('covers-manifest.js','// Generated from IGDB. Exact + unique IGDB alternative-name recovery.\nwindow.SHELFCHECK_COVERS='+JSON.stringify(obj)+';\nwindow.SHELFCHECK_COVER_META='+JSON.stringify(meta)+';\n');fs.writeFileSync('cover-audit.json',JSON.stringify({...meta,recovered,still,rows:out},null,2));console.log(JSON.stringify(meta,null,2));