#!/usr/bin/env python3
"""Recover ShelfCheck cover fronts from PriceCharting using only reviewed title aliases.

Safety rule: an unresolved ShelfCheck identity may only inherit a PriceCharting image when
PriceCharting's PS4 product title exactly matches one of the repo's reviewed aliases for that
same identity ID (punctuation-only compact equality is also allowed), and the image passes the
same straight portrait + strong blue PS4-header gate used by the existing retail recovery.
"""
import ast
import importlib.util
import json
import os
import re
import time
import urllib.parse
from collections import Counter, defaultdict

BASE_SCRIPT = 'tools/pricecharting-cover-recovery.py'
RUNTIME = 'audit-out/cover-runtime-qa.json'
OUT_JS = 'cover-pricecharting-retail.js'
OUT_JSON = 'audit-out/pricecharting-alias-cover-recovery.json'
ALIAS_FILES = ['price-import-v037.js', 'price-alias-v039.js', 'price-alias-v040.js']

spec = importlib.util.spec_from_file_location('shelfcheck_pc_base', BASE_SCRIPT)
pc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pc)


def parse_reviewed_aliases():
    """Return identity id -> reviewed PriceCharting spellings from the repo's vetted ledgers."""
    by_id = defaultdict(list)
    literal_re = re.compile(r'''("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')\s*:\s*(\d+)''')
    for path in ALIAS_FILES:
        if not os.path.exists(path):
            continue
        text = open(path, encoding='utf-8').read()
        for m in literal_re.finditer(text):
            literal, raw_id = m.groups()
            try:
                title = ast.literal_eval(literal)
            except Exception:
                continue
            if not isinstance(title, str) or not title.strip():
                continue
            identity_id = int(raw_id)
            n = pc.norm(title)
            if n and all(pc.norm(old) != n for old in by_id[identity_id]):
                by_id[identity_id].append(title.strip())
    return by_id


def load_existing_meta():
    if not os.path.exists(OUT_JS):
        return {}
    text = open(OUT_JS, encoding='utf-8').read()
    m = re.search(r'window\.SHELFCHECK_PRICECHARTING_META=(\{.*?\});', text, re.S)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except Exception:
        return {}


def write_cover_layer(covers, original_meta, alias_meta):
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// Generated by ShelfCheck PriceCharting physical-cover recovery. Accepted PS4 front covers only.\n')
        f.write('window.SHELFCHECK_PRICECHARTING_COVERS=' + json.dumps(covers, separators=(',', ':')) + ';\n')
        f.write('window.SHELFCHECK_PRICECHARTING_META=' + json.dumps(original_meta, separators=(',', ':')) + ';\n')
        f.write('window.SHELFCHECK_PRICECHARTING_ALIAS_META=' + json.dumps(alias_meta, separators=(',', ':')) + ';\n')
        f.write("if(typeof document!=='undefined'){(()=>{let n=0;const apply=()=>{n++;window.SHELFCHECK_TITLE_COVERS={...(window.SHELFCHECK_TITLE_COVERS||{}),...(window.SHELFCHECK_PRICECHARTING_COVERS||{})};if(window.SHELFCHECK_COVER_ART?.repaint)window.SHELFCHECK_COVER_ART.repaint();else if(n<80)setTimeout(apply,100)};if(document.readyState==='complete')apply();else window.addEventListener('load',apply,{once:true})})()}\n")


def main():
    runtime = json.load(open(RUNTIME, encoding='utf-8'))
    reviewed = parse_reviewed_aliases()
    existing = pc.load_existing()
    original_meta = load_existing_meta()

    unresolved = []
    seen_ids = set()
    for bucket in ('review', 'watch', 'fallback'):
        for row in runtime.get(bucket, []):
            identity_id = row.get('id')
            title = row.get('title')
            if not isinstance(identity_id, int) or not title or identity_id in seen_ids:
                continue
            seen_ids.add(identity_id)
            canonical = pc.norm(title)
            if canonical in existing:
                continue
            aliases = [a for a in reviewed.get(identity_id, []) if pc.norm(a) != canonical]
            if aliases:
                unresolved.append({
                    'id': identity_id,
                    'title': title,
                    'bucket': bucket,
                    'reason': row.get('reason'),
                    'aliases': aliases,
                })

    print('Unresolved identities with reviewed aliases:', len(unresolved))
    print('Existing PriceCharting cover fronts preserved:', len(existing))

    covers = dict(existing)
    accepted = []
    no_match = []
    rejected = []
    errors = []
    region_counts = Counter()
    match_counts = Counter()

    for i, target in enumerate(unresolved, 1):
        viable = []
        target_rejections = []
        target_errors = []
        for alias_index, alias in enumerate(target['aliases']):
            try:
                query = urllib.parse.quote(alias + ' Playstation 4')
                final, raw = pc.request(pc.SEARCH + query)
                candidates = pc.parse_candidates(final, raw)
                for candidate in candidates:
                    method = None
                    if pc.norm(candidate.get('title')) == pc.norm(alias):
                        method = 'reviewed_alias_exact'
                    elif pc.compact(candidate.get('title')) == pc.compact(alias):
                        method = 'reviewed_alias_compact_exact'
                    if not method:
                        continue
                    image = candidate.get('image') or pc.image_from_product(candidate['url'])
                    if not image:
                        target_rejections.append({
                            'alias': alias,
                            'matchedTitle': candidate.get('title'),
                            'region': candidate.get('region'),
                            'productUrl': candidate.get('url'),
                            'reason': 'no_product_image',
                        })
                        continue
                    ok, metrics = pc.validate_image(image)
                    if not ok:
                        target_rejections.append({
                            'alias': alias,
                            'matchedTitle': candidate.get('title'),
                            'region': candidate.get('region'),
                            'productUrl': candidate.get('url'),
                            'image': image,
                            'reason': 'failed_retail_front_gate',
                            'metrics': metrics,
                        })
                        continue
                    viable.append({
                        'alias': alias,
                        'aliasIndex': alias_index,
                        'matchedTitle': candidate.get('title'),
                        'matchMethod': method,
                        'region': candidate.get('region'),
                        'regionRank': candidate.get('regionRank', 99),
                        'productUrl': candidate.get('url'),
                        'image': image,
                        'metrics': metrics,
                    })
            except Exception as exc:
                target_errors.append({'alias': alias, 'error': str(exc)[:220]})
            time.sleep(0.12)

        if viable:
            viable.sort(key=lambda c: (
                c['regionRank'],
                0 if c['matchMethod'] == 'reviewed_alias_exact' else 1,
                c['aliasIndex'],
                c['productUrl'],
            ))
            chosen = viable[0]
            covers[pc.norm(target['title'])] = chosen['image']
            row = {**target, **{k: v for k, v in chosen.items() if k not in ('aliasIndex', 'regionRank')}}
            accepted.append(row)
            region_counts[chosen['region']] += 1
            match_counts[chosen['matchMethod']] += 1
        elif target_rejections:
            rejected.append({**target, 'attempts': target_rejections})
        elif target_errors:
            errors.append({**target, 'attempts': target_errors})
        else:
            no_match.append(target)

        if i % 10 == 0 or i == len(unresolved):
            print(f"processed {i}/{len(unresolved)} accepted={len(accepted)} no_match={len(no_match)} rejected={len(rejected)} errors={len(errors)}")

    summary = {
        'reviewedAliasFiles': ALIAS_FILES,
        'reviewedIdentityCount': len(reviewed),
        'targetsWithReviewedAliases': len(unresolved),
        'preserved': len(existing),
        'acceptedThisRun': len(accepted),
        'totalPriceChartingCovers': len(covers),
        'noExactAliasMatch': len(no_match),
        'rejectedByImageGate': len(rejected),
        'errors': len(errors),
        'regionCounts': dict(region_counts),
        'matchMethods': dict(match_counts),
        'standard': 'same identity id from reviewed ShelfCheck alias ledger + exact/compact-exact PS4 product title + straight portrait + strong blue PS4 header',
    }

    os.makedirs('audit-out', exist_ok=True)
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump({
            'summary': summary,
            'accepted': accepted,
            'noMatch': no_match,
            'rejected': rejected,
            'errors': errors,
        }, f, indent=2, ensure_ascii=False)
    write_cover_layer(covers, original_meta, summary)
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
